### ISSUE TITLE
Issue of formatting scss filename with underscore

### ISSUE THREAD

**Issue by bgiraffe** [mrmlnc/vscode-csscomb#15] opened 2016-09-13 09:20 UTC
Hi guys, first at all, great job and thank you.

I have updated to 2.0, and i found that if scss filename with underscore like "_base.scss", the extension is not working, is anything i missed?

Thanks for your time.

**Comment by mrmlnc** [comment] 2016-09-13 10:25
Hello, @bgiraffe ,

Firstly, thank you for opening this issue. 

I can't reproduce your problem on Windows 10. You can help fix the problem, if you provide small code examples and your Editor settings.

**Comment by bgiraffe** [comment] 2016-09-17 05:34
Sorry for the late reply, after your reply, i have try a bit in other file, it's working...

I have debug it one by one of my css code, here is the code cause the plugin not work, 

`#footer {
  background-color: $bgColor;
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 2.5rem;

  > div {
    padding: $sgap;
    text-align: right;
  }
}`

And i have install the original csscomb npm and test to format the css code at command line, it is worked.

Hopes it's help!

**Comment by bgiraffe** [comment] 2016-09-17 05:46
I think it is the same issue to #16 because i have check my command line csscomb version is 3.1.7, i think it is the latest release right? It is better to stick to the latest stable release.

**Comment by mrmlnc** [comment] 2016-09-17 09:17
@bgiraffe,

I'll close this issue as duplicate of #16. I'll work on him today.

**Closed by mrmlnc** 2016-09-17 09:17 UTC
Labels: bug, upstream

**Comment by bgiraffe** [comment] 2016-09-17 09:18
Thx, mate!
