### ISSUE TITLE
csscomb error

### ISSUE THREAD

**Issue by NateLing** [mrmlnc/vscode-csscomb#51] opened 2016-12-14 05:54 UTC
macos 10.12.2
vscode 1.7.2
node 7.2.1

![image](https://cloud.githubusercontent.com/assets/9606668/21171090/8d3adf90-c204-11e6-9cac-5fe2cdac579e.png)

**Comment by mrmlnc** [comment] 2016-12-14 08:31
Hello, @NateLing,

Firstly, thanks that you use this plugin and open this Issue.

Unfortunately, I must ask you to provide your config file, editor settings for csscomb and file that is causing this error, because without it I wouldn't be able to understand the error.

**Comment by NateLing** [comment] 2016-12-15 01:43
Hello, @mrmlnc 


this is my vscode setting:
```json
{
    "csscomb.formatOnSave": true,
    "csscomb.preset": "csscomb",
    "csscomb.preset":{
        "color-shorthand": true,
        "leading-zero": false,
        "quotes": "single",
        "remove-empty-rulesets": true,
        "space-after-colon": 1,
        "space-before-colon": 1,
        "vendor-prefix-align": true
    },
    "csscomb.useLatestCore":true,
    "editor.wrappingColumn": 0,
    "files.autoSave": "onWindowChange",
    "workbench.editor.enablePreview": false,
    "eslint.autoFixOnSave": true
}
```

this is an test less file content:

```less
.text{
    font-size: 14px;
    line-height: 1.5em;
    white-space: normal;
    word-wrap: break-word;
}
```

this is my plugin list:

![image](https://cloud.githubusercontent.com/assets/9606668/21208734/e991b358-c2aa-11e6-835c-8f176643ac94.png)

**Comment by mrmlnc** [comment] 2016-12-15 05:52
Hmm, i cannot reproduce this behaviour with your settings:

![2016-12-15_08-51-36](https://cloud.githubusercontent.com/assets/7034281/21213163/bad58136-c2a3-11e6-9f22-3e3f469816e0.gif)

Maybe you have workspace settings inside `.vscode/settings`?

**Comment by NateLing** [comment] 2016-12-15 06:12
there is no `.vscode/settings`,i will download the source code and debug it. :smile:

**Comment by NateLing** [comment] 2016-12-16 01:41
@mrmlnc  it works well now. i had uninstall vscode then reinstall it. 😃

**Comment by mrmlnc** [comment] 2016-12-17 13:18
Well, I can close this issue? 

If the problem not solved, let me know :)

**Closed** 2016-12-17 15:09 UTC
Labels: needs more info

**Comment by bsed** [comment] 2017-03-07 07:15
could not use .csscomb.json in project
